import { nanoid } from "@reduxjs/toolkit";

const moviesData = {
    movies: {
      "1": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/6565/1732508956565-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/4683/1732508914683-v",
        About:{
          year: "2024",
          lag: "4 Languages",
          certif: "A",
          runTime: "1h 58min",
        },
        genre:{
          Action: true,
          Adventure: true,
          Comedy: false,
          Drama: false,
          Horror: true,
          Mystery: false,
          Romance: false,
          Science_Fiction: true,
          Thriller: true,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: true,
          Tamil:true
        },
        description: "young space colonizers come face-to-face with the ultimate horror.",
        title: "Skeleton crew",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/3788/1732508933788-t",
        type: "recommend"
      },
      "2": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/7497/1731416817497-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/4725/1731416764725-v",
        About:{
          year: "2024",
          lag: "4 Languages",
          certif: "A",
          runTime: "1h 58min",
        },
        genre:{
          Action: true,
          Adventure: true,
          Comedy: true,
          Drama: false,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: true,
          Tamil:true
        },
        description: "In a hilarious and chaotic twist of fate, Deadpool (Ryan Reynolds) finds himself entangled in the fabric of the multiverse. ",
        title: "DeadPool & Wolverine",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/1375/1731416791375-t",
        type: "recommend"
      },
      "3": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/1822/1731317621822-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/1199/1731317591199-v",
        About:{
          year: "2024",
          lag: "4 Languages",
          certif: "A",
          runTime: "1h 58min",
        },
        genre:{
          Action: true,
          Adventure: true,
          Comedy: false,
          Drama: false,
          Horror: true,
          Mystery: false,
          Romance: false,
          Science_Fiction: true,
          Thriller: true,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: true,
          Tamil:true
        },
        description: "Young space colonizers come  face-to-face with the ultiimate horror.",
        title: "Aline Romulus",
        titleimg:"https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/4650/1731317604650-t",
        type: "recommend"
      },
      "4": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/9576/1732289849576-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/5391/1732289795391-v",
          About:{
          year: "2024",
          seasson:"1",
          lag: "3 Languages",
          certif: "UA/16",
          runTime: "58min",
        },
        genre:{
          Action: false,
          Adventure: false,
          Comedy: false,
          Drama: true,
          Horror: false,
          Mystery: false,
          Romance: true,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: false,
          Telugu: true,
          Tamil:true
        },
        description: "Tow families clash over societal and caste differences , spering  a sage of reverge .All",
        title: "Thukra ke mera pyaar",
        titleimg:"https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/1710/1732214011710-t",
        type: "recommend"
      },
      "5": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/9188/1731497329188-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/7571/1731497207571-v",
        About:{
          year: "2024",
          seasson:"5",
          lag: "7 Languages",
          certif: "UA/13+",
          runTime: "30min",
        },
        genre:{
          Action: true,
          Adventure: true,
          Comedy: false,
          Drama: false,
          Horror: true,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
          Mthology:true,
          Animation:true,
          
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: true,
          Tamil:true,
          Malayalam:true,
          Gujarati:true,
          Marathi:true,

        },
        description: "Hanuman descends into  patal  loka a save the divine princes. As he navigates this mysterious world , Ahiranvan  unleashes his castaclymic plan. ",
        title: "The legend of hanuman",
        titleimg:"https://img10.hotstar.com/image/upload/f_auto,h_156/sources/r1/cms/prod/3091/1731497343091-t",
        type: "recommend"
      },
      "6": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/6106/1730982356106-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/8845/1731068038845-v",
          About:{
          year: "2024",
          lag: "5 Languages",
          certif: "UA/13+",
          runTime: "2h 27m",
        },
        genre:{
          Action: true,
          Adventure: true,
          Comedy: false,
          Drama: false,
          Horror: false,
          Mystery: true,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: true,
          Tamil:true,
          Malayalam:true,
        },
        description: "Drawn into the legacy of the 'Chiyothivilakku ' , Ajayan confronts the tangled choices of his ancestors , each revealing shadows that stretch across time. " ,
        title: "ARM",
        titleimg:"https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/2404/1730982342404-t",
        type: "recommend"
      },
      "7": {
        id:nanoid(),

        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/8500/1729950438500-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/7960/1729950367960-v",
          About:{
          year: "2024",
          lag: "1 Languages",
          certif: "U/A7+",
          runTime: "1h 58min",
        },
        genre:{
          Action: true,
          Adventure: false,
          Comedy: false,
          Drama: false,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: true,
          Reality:true,

        },
        Language:{
          Hindi: true,
          English: false,
          Telugu: false,
          Tamil:true
        },
        description: "Join the speactacular audio launch of Amaran  a thrilling  biographiacal action war film dfeaturing Shivakarthikayan and sai Pallavi.",
        title: "AMARAN",
        titleimg:"https://img10.hotstar.com/image/upload/f_auto,h_156/sources/r1/cms/prod/1659/1729950401659-t",
        type: "recommend"
      },
      "8": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/1113/1731323401113-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/9076/1731484439076-v",
          About:{
          year: "2024",
          lag: "1 Languages",
          certif: "U/A 7+",
          runTime: "2h 38min",
        },
        genre:{
          Action: false,
          Adventure: false,
          Comedy: false,
          Drama: true,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: false,
          Telugu: false,
          Tamil:false
        },
        description: "Resilient and headStrong Vir dreams of lauching an airline  service for thecommon man . With is mission aligned , can he soarto new heights ?",
        title: "Sarfira",
        titleimg:"https://img10.hotstar.com/image/upload/f_auto,h_156/sources/r1/cms/prod/1638/1731323411638-t",
        type: "recommend"
      },
      "9": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/8909/1721799688909-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/7587/1713534377587-v",
        About:{
          year: "2024",
          lag: "3 Languages",
          certif: "U",
          runTime: "2h 33min",
        },
        genre:{
          Action: false,
          Adventure: false,
          Comedy: false,
          Drama: true,
          Horror: false,
          Mystery: false,
          Romance: true,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: false,
          Telugu: true,
          Tamil:true
        },
        description: "one a letter-delivering task , afreen learns of 20-year-old romance set amidst a war . Her request to trace the loves  makes her embrace humanity beyond borders.  ",
        titleimg:"https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/7298/1721799697298-t",
        title: "Sita Ram",
        type: "recommend"
      },
      "10": {
        id:nanoid(),

        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/1791/1611791-i-3b22c4f693bd",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/9003/1639003-v-31cc8eeb198f",
          About:{
          year: "2022",
          lag: "4 Languages",
          certif: "UA/16+",
          runTime: "2h 51min",
        },
        genre:{
          Action: true,
          Adventure: false,
          Comedy: false,
          Drama: false,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: true,
          War: false,
        },
        Language:{
          Hindi: true,
          Telugu: true,
          Tamil:true,
          Malayalam: true,
          English: false
        },
        description: "A convet investigation changes its course when special officer Amar counters an unrelenting Vikaram and his pursuit to take down a notorious drug cartel.",
        titleimg:"https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/1790/1611790-t-b372576e5b89",
        title: "Vikaram",
        type: "Entertainment"
      },
      "11": {
        id:nanoid(),

        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/8403/1721624308403-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/6092/1710929776092-v",
          About:{
          year: "2019",
          lag: "4 Languages",
          certif: "U/A16+",
          runTime: "2h 23min",
        },
        genre:{
          Action: false,
          Adventure: true,
          Comedy: false,
          Drama: true,
          Horror: false,
          Mystery: false,
          Romance: true,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: true,
          Tamil:true
        },
        description: "Divided bt time , untied by tragic incident .In a bittersweet reunion, seven middle-aged friends take a walk down the memmory lare at the least expected place.",
        titleimg:"https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/6872/1721624316872-t",
        title: "chhichhore",
        type: "Entertainment"
      },
      "12": {
        id:nanoid(),

        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/6482/1721630406482-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/1064/1710950101064-v",
          About:{
          year: "2024",
          lag: "4 Languages",
          certif: "UA/16+",
          runTime: "2h 14min",
        },
        genre:{
          Action: true,
          Adventure: false,
          Comedy: false,
          Drama: false,
          Horror: true,
          Mystery: true,
          Romance: false,
          Science_Fiction: false,
          Thriller: true,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: true,
          Tamil:true
        },
        description: "When a small town gets plunged into the nightmare of serial killings rookie cop Arjan embarks on a crase for truth and unravels a gruesome conspiracy.",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/6453/1721630416453-t",
        title: "cuttputlli",
        type: "Entertainment"
      },
      "13": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/5545/1375545-i-4b156857922b",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/3649/1711465823649-v",
          About:{
          year: "2019",
          lag: "4 Languages",
          certif: "UA/7+",
          runTime: "2h 19min",
        },
        genre:{
          Action: false,
          Adventure: false,
          Comedy: false,
          Drama: true,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: true,
          Tamil:true
        },
        description: "When 50 million bucks are at stake , six eccentric  people will do whatever it takes , including braving the wild . who Will win this race against time ? ",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/5547/1375547-t-5feab2236338",
        title: "TotalDhamaal",
        type: "Entertainment"
      },
      "14": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/6459/1366459-i-e2c44bc5be9b",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/1327/441327-v",
          About:{
          year: "2019",
          lag: "1 Languages",
          certif: "U/A13+",
          runTime: "1h 54min",
        },
        genre:{
          Action: true,
          Adventure: true,
          Comedy: false,
          Drama: true,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: false,
          Telugu: false,
          Tamil:false
        },
        description: "Back in his hometown after years , Raj befriends Bhola , an elephant .As time passes , he discovers a deep-rooted poaching scandal , which changes his life forever .",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_156/sources/r1/cms/prod/6461/1366461-t-2022b2a59e2d",
        title: "junglee",
        type: "Entertainment"
      },
      "15": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/1531/1721200231531-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/3879/1710936653879-v",
          About:{
          year: "2021",
          lag: "1 Languages",
          certif: "U/A16+",
          runTime: "2h 8min",
        },
        genre:{
          Action: true,
          Adventure: true,
          Comedy: false,
          Drama: false,
          Horror: true,
          Mystery: false,
          Romance: false,
          Science_Fiction: true,
          Thriller: true,
          War: false,
        },
        Language:{
          Hindi: true,
          English: false,
          Telugu: false,
          Tamil:false
        },
        description: "Two brothers Vibhooti and Chiraunji have 'fought' their share of ghosts. However, a new case forces them to rethink  their own abilities and beliefs.  ",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/8032/1721200248032-t",
        title: "BhootPolice",
        type: "Entertainment"
      },
      "16": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/5545/1625545-i-b06648dd9679",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/3261/1710950343261-v",
          About:{
          year: "2022",
          lag: "4 Languages",
          certif: "U/A16+",
          runTime: "2h 20min",
        },
        genre:{
          Action: true,
          Adventure: true,
          Comedy: false,
          Drama: false,
          Horror: false,
          Mystery: true,
          Romance: false,
          Science_Fiction: false,
          Thriller: true,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: true,
          Tamil:true
        },
        description: "When a series of misterious events stris pandemonium in a village ,an eccentric cop Vikrant Rona Sets Out to solve the case wherein everyone is under the radar. ",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/5544/1625544-t-15e7babe377e",
        title: "Vikrant Rona",
        type: "Entertainment"
      },
      "17": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/8141/1368141-i-0afa15e1ae92",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/7416/957416-v",
          About:{
          year: "2015",
          lag: "2 Languages",
          certif: "UA/16+",
          runTime: "2h 33min",
        },
        genre:{
          Action: true,
          Adventure: true,
          Comedy: false,
          Drama: false,
          Horror: true,
          Mystery: true,
          Romance: false,
          Science_Fiction: false,
          Thriller: true,
          War: false,
        },
        Language:{
          Hindi: true,
          English: false,
          Telugu: false,
          Tamil:true
        },
        description: "Post 26/11 Mumbai attacks , a specail intelligence task force will stop at nothing to foil another such assauit on the indian soil.",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/8923/1418923-t-be0745b98773",
        title: "BABY",
        type: "Entertainment"
      },







      "18": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/9705/1369705-i-6639ebe04527",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/8105/1118105-v-cf275eb3c3f2",
          About:{
          year: "2007",
          lag: "1 Languages",
          certif: "U/A 13+",
          runTime: "2h 28min",
        },
        genre:{
          Action: false,
          Adventure: false,
          Comedy: true,
          Drama: false,
          Horror: true,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: true,
          War: false,
        },
        Language:{
          Hindi: true,
          English: false,
          Telugu: false,
          Tamil:false
        },
        description: "Siddarth and Avni's life changes when they move into his ancestral home .In this maza of superstitions, how will  they find their way ?",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/9707/1369707-t-ef4d78b5c602",
        title: "BhoolBhulaiyaa",
        type: "Comdey"
      },
      "19": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/2431/1721626542431-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/9166/1710929909166-v",
          About:{
          year: "2019",
          lag: "1 Languages",
          certif: "U/A 13+",
          runTime: "2h 15m",
        },
        genre:{
          Action: false,
          Adventure: false,
          Comedy: true,
          Drama: true,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: false,
          Telugu: false,
          Tamil:false
        },
        description:"1419 , love between  three couples succumbed  to an evil ploy! History repeats ,they reincarnate after six centuries , albeit with the wrong partners.",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/9140/1721626559140-t",
        title: "HouseFull 4",
        type: "Comdey"
      },
      "20": {
        id:nanoid(),

        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/2172/1707277262172-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/5953/525953-v",
          About:{
          year: "2019",
          lag: "1 Languages",
          certif: "U/A 13+",
          runTime: "2h 14min",
        },
        genre:{
          Action: false,
          Adventure: false,
          Comedy: true,
          Drama: true,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: false,
          Telugu: false,
          Tamil:false
        },
        description:"50-year-old Ashish has fallen in love with Ayesha , who is half his age . Their Romance turns into a comedy , when he takes her to meet  his parnets and ex-wife.",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_156/sources/r1/cms/prod/2014/1707277272014-t",
        title: "De De pyaar de",
        type: "Comdey"
      },
      "21": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/180/1724530470180-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/4606/1724530174606-v",
          About:{
          year: "2024",
          lag: "3 Languages",
          certif: "U/A 16+",
          runTime: "2h ",
        },
        genre:{
          Action: false,
          Adventure: false,
          Comedy: true,
          Drama: true,
          Horror: true,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: false,
          Telugu: true,
          Tamil:true,
          
        },
        description:"Chetukwadi ,Bittu unfurls  the horrors of  a vengeful  spirit. Rawakenend and eager ti marry , munjya follows his like a shadow.And eerie ride begins!. ",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/4319/1724530484319-t",
        title: "Munjay",
        type: "Comdey"
      },

      "22": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/9928/1649928-i-11e2344bce91",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/old_images/vertical/MOVIE/7132/1000007132/1000007132-v",
          About:{
          year: "2024",
          lag: "4 Languages",
          certif: "A",
          runTime: "1h 58min",
        },
        genre:{
          Action: false,
          Adventure: false,
          Comedy: true,
          Drama: true,
          Horror: false,
          Mystery: false,
          Romance: true,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: false,
          Telugu: false,
          Tamil:false
        },
        description: "Jassi falls head over heels in love with Sukhmit, only to discover her family is out to finish him over an old family feud . How will love triumph over revenge?",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/9927/1649927-t-bd2ab3005d5e",
        title: "Jolly LLB",
        type: "Comdey"
      },
      "23": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/8292/1707211568292-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/7166/1477166-v-a1c62df76321",
          About:{
          year: "2006",
          lag: "1 Languages",
          certif: "U/A 13+",
          runTime: "2h 21min",
        },
        genre:{
          Action: true,
          Adventure: true,
          Comedy: true,
          Drama: true,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: false,
          Telugu: false,
          Tamil:false
        },
        description: "Spinning a web of lies, four crooks seek shelter in a bungalow owned by a blind couple.But hilarity ensues when they all fall in love with a girl next door.",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/6195/1707211576195-t",
        title: "GolMaal Fun Unlimated",
        type: "Comdey"
      },
      "24": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/7124/1707274977124-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/7309/177309-v",
          About:{
          year: "2028",
          lag: "1 Languages",
          certif: "U",
          runTime: "2h 3min",
        },
        genre:{
          Action: false,
          Adventure: false,
          Comedy: true,
          Drama: true,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: false,
          Telugu: false,
          Tamil:false
        },
        description: "Getting a new  Sibling at 25 is the last thing Nakul  expected. Will he ever come to terms with the  embarrassing 'good news' of his parents being pregnant?  ",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/4534/1707274994534-t",
        title: "Badhaai  ho",
        type: "Comdey"
      },
      "25": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/9253/1721791819253-i",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/7803/1712209007803-v",
          About:{
          year: "2020",
          lag: "1 Languages",
          certif: "U/A 16+",
          runTime: "2h 21min",
        },
        genre:{
          Action: true,
          Adventure: false,
          Comedy: true,
          Drama: false,
          Horror: true,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: false,
          Telugu: false,
          Tamil:false
        },
        description: "Aasif belief in logic and science  shatters when he gets possessed  by a ghost .what starts as a comical  journey soon unearths a dark secret. ",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/101/1721791830101-t",
        title: "Laxmii",
        type: "Comdey"
      },



      "26": {
        id:nanoid(),

        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/7982/1407982-i-452a8daf932d",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/5151/875151-v",
          About:{
          year: "2019",
          lag: "4 Languages",
          certif: "U/A 7+",
          runTime: "2h 10m",
        },
        genre:{
          Action: true,
          Adventure: true,
          Comedy: true,
          Drama: true,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: true,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: true,
          Tamil:true
        },
        description: "In this live-action retelling of 1992 classic ,Aladdin and a power-hungry Grand Vizier  vie for a lamp that can make their deepest wishes come true.",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_156/sources/r1/cms/prod/7984/1407984-t-18fe2b069354",
        title: "Aladdin",
        type: "DisneyMovies"
      },
      "27": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/9293/809293-i",
        cardImg:"https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/5241/875241-v",
          About:{
          year: "2019",
          lag: "4 Languages",
          certif: "U/A 7+",
          runTime: "1h 58min",
        },
        genre:{
          Action: false,
          Adventure: true,
          Comedy: false,
          Drama: false,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
          fantasy:true
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: true,
          Tamil:true
        },
        description: "In the African savanna , a young prince overcomes betrayal  and tragedy to assume his rightful place on Pride Rock.",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_156/sources/r1/cms/prod/8700/1418700-t-540523988b7d",
        title: "The Lion King",
        type: "DisneyMovies"
      },
      "28": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/3278/1373278-i-aa85c4cf19fe",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/5557/675557-v",
          About:{
          year: "21989",
          lag: "3 Languages",
          certif: "U",
          runTime: "1h 22min",
        },
        genre:{
          Action: false,
          Adventure: false,
          Comedy: false,
          Drama: false,
          Horror: false,
          Mystery: false,
          Musical:true,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          fantasy:true,
          Animation:true,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: false,
          Tamil:true
        },
        description: "Ariel, a mermaid , is off on adventure to save her father's beloved kingdom  from the sea witch Ursula , with her best friends Flounder and Sabastian. ",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_156/sources/r1/cms/prod/3282/1373282-t-07fa82235832",
        title: "The Little Mermaid",
        type: "DisneyMovies"
      },
      "29": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/4278/1374278-i-00cd5b606a7a",
        cardImg: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/5402/675402-v",
          About:{
          year: "2003",
          lag: "4 Languages",
          certif: "U/A 13+",
          runTime: "2h 23min",
        },
        genre:{
          Action: true,
          Adventure: true,
          Comedy: false,
          Drama: false,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: true,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: false,
          Tamil:true
        },
        description: "When captain Barbossa Kindnaps the Governer's daughter and her would-be suitor, Will Turner,coerces Captain Jack Sparrow into rescuing her .",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/4280/1374280-t-4195a0ffe804",
        title: "Pirtes of Caribbean",
        type: "DisneyMovies"
      },
      "30": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/8281/1408281-i-c37b76fe5525",
        cardImg:    "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/5908/1075908-v-74780cbd6355",
          About:{
          year: "2021",
          lag: "5 Languages",
          certif: "U?A 13+",
          runTime: "2h 7min",
        },
        genre:{
          Action: true,
          Adventure: true,
          Comedy: true,
          Drama: false,
          Horror: false,
          Mystery: true,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: true,
          Tamil:true,
          Malayalam: true
        },
        description: "A rollicking thrill-ride down the Amazon with wisercracking skipper Frank Wolff and intrepid  researcher Dr.Lily Houghton.",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_156/sources/r1/cms/prod/8284/1408284-t-82f4382ce464",
        title: "Jungle Curise",
        type: "DisneyMovies"
      },
      "31": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/1209/1371209-i-096cf5035b55",
        cardImg:"https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/5454/675454-v",
          About:{
          year: "2017",
          lag: "2 Languages",
          certif: "U/A 7+",
          runTime: "2h 9min",
        },
        genre:{
          Action: false,
          Adventure: false,
          Comedy: true,
          Drama: true,
          Horror: false,
          Mystery: true,
          Romance: true,
          Musical:true,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: false,
          Tamil:false
        },
        description: "Belle is taken prisoner by Beast in his castle.Despite her fears, she looks beyond the Beast's exterior to realized the soul of the true Prince within.",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_156/sources/r1/cms/prod/1212/1371212-t-5bebe57fe29e",
        title: "Beauty and The  Beast",
        type: "DisneyMovies"
      },
      "32": {
        id:nanoid(),
        backgroundImg: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/5569/1375569-i-bd62d3b6884f",
        cardImg:  "https://img10.hotstar.com/image/upload/f_auto,q_90,w_256/sources/r1/cms/prod/1220/871220-v",
          About:{
          year: "2019",
          lag: "2 Languages",
          certif: "U/A 7+",
          runTime: "1h 59min",
        },
        genre:{
          Action: false,
          Adventure: true,
          famliy:true,
          fantasy:true,
          Comedy: false,
          Drama: false,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: false,
          Tamil:false
        },
        description: "Maleficent and her goddaughter Aurora Begin to Question their tangled ties as they are pulled in different directions by the impending wedding.",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_156/sources/r1/cms/prod/5571/1375571-t-8cf1f7b6e684",
        title: "Maleficent Mistress of Evil",
        type: "DisneyMovies"
      }, 

      "33": {
        id:nanoid(),
        backgroundImg: "",
        cardImg:"",
          About:{
          year: "2024",
          seasson:"3",
          lag: "2 Languages",
          certif: "U/A 7+",
          runTime: "1h 59min",

        },
        genre:{
          Action: false,
          Adventure: false,
          famliy:false,
          fantasy:false,
          Comedy: false,
          Drama: false,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: false,
          Tamil:false
        },
        description: "",
        titleimg: "https://img10.hotstar.com/image/upload/f_auto,h_124/sources/r1/cms/prod/727/1630727-t-34b807858ae7",
        title: "What If...?",
        type: "CommingSoon"
      }, 
      "34": {
        id:nanoid(),
        backgroundImg: "",
        cardImg:"",
          About:{
          year: "2019",
          lag: "2 Languages",
          certif: "U/A 7+",
          runTime: "1h 59min",
        },
        genre:{
          Action: false,
          Adventure: false,
          famliy:false,
          fantasy:false,
          Comedy: false,
          Drama: false,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: false,
          Tamil:false
        },
        description: "",
        titleimg: "",
        title: "",
        type: "CommingSoon"
      }, 
      "35": {
        id:nanoid(),
        backgroundImg: "",
        cardImg:"",
          About:{
          year: "2019",
          lag: "2 Languages",
          certif: "U/A 7+",
          runTime: "1h 59min",
        },
        genre:{
          Action: false,
          Adventure: false,
          famliy:false,
          fantasy:false,
          Comedy: false,
          Drama: false,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: false,
          Tamil:false
        },
        description: "",
        titleimg: "",
        title: "",
        type: "CommingSoon"
      }, 
      "36": {
        id:nanoid(),
        backgroundImg: "",
        cardImg:"",
          About:{
          year: "2019",
          lag: "2 Languages",
          certif: "U/A 7+",
          runTime: "1h 59min",
        },
        genre:{
          Action: false,
          Adventure: false,
          famliy:false,
          fantasy:false,
          Comedy: false,
          Drama: false,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: false,
          Tamil:false
        },
        description: "",
        titleimg: "",
        title: "",
        type: "CommingSoon"
      }, 
      "37": {
        id:nanoid(),
        backgroundImg: "",
        cardImg:"",
          About:{
          year: "2019",
          lag: "2 Languages",
          certif: "U/A 7+",
          runTime: "1h 59min",
        },
        genre:{
          Action: false,
          Adventure: false,
          famliy:false,
          fantasy:false,
          Comedy: false,
          Drama: false,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: false,
          Tamil:false
        },
        description: "",
        titleimg: "",
        title: "",
        type: "CommingSoon"
      }, 
      "38": {
        id:nanoid(),
        backgroundImg: "",
        cardImg:"",
          About:{
          year: "2019",
          lag: "2 Languages",
          certif: "U/A 7+",
          runTime: "1h 59min",
        },
        genre:{
          Action: false,
          Adventure: false,
          famliy:false,
          fantasy:false,
          Comedy: false,
          Drama: false,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: false,
          Tamil:false
        },
        description: "",
        titleimg: "",
        title: "",
        type: "CommingSoon"
      }, 
      "39": {
        id:nanoid(),
        backgroundImg: "",
        cardImg:"",
          About:{
          year: "2019",
          lag: "2 Languages",
          certif: "U/A 7+",
          runTime: "1h 59min",
        },
        genre:{
          Action: false,
          Adventure: false,
          famliy:false,
          fantasy:false,
          Comedy: false,
          Drama: false,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: false,
          Tamil:false
        },
        description: "",
        titleimg: "",
        title: "",
        type: "CommingSoon"
      }, 
      "40": {
        id:nanoid(),
        backgroundImg: "",
        cardImg:"",
          About:{
          year: "2019",
          lag: "2 Languages",
          certif: "U/A 7+",
          runTime: "1h 59min",
        },
        genre:{
          Action: false,
          Adventure: false,
          famliy:false,
          fantasy:false,
          Comedy: false,
          Drama: false,
          Horror: false,
          Mystery: false,
          Romance: false,
          Science_Fiction: false,
          Thriller: false,
          War: false,
        },
        Language:{
          Hindi: true,
          English: true,
          Telugu: false,
          Tamil:false
        },
        description: "",
        titleimg: "",
        title: "",
        type: "CommingSoon"
      }, 
     
      
  }
};
  
  export default moviesData;
  